export interface RandomusersInterface {
  id: number,
  uid: string,
  password: string,
  first_name: string,
  last_name: string,
  username: string,
  email: string,
  avatar: string,
  gender: string,
  phone_number: number | string,
  social_insurance_number: string,
  date_of_birth: any,
  employment: any,
  address: any,
  credit_card: any,
  subscription: any,
}
